### ISSUE TITLE
hoppscotch Support

### ISSUE THREAD

**Issue by vncloudsco** [TinyActive/cosmos-servapps-official#34]
**Is your feature request related to a software? Please describe.**

Hoppscotch is a lightweight, web-based API development suite. It was built from the ground up with ease of use and accessibility in mind providing all the functionality needed for API developers with minimalist, unobtrusive UI

**Describe the solution you'd like**
Hoppscotch

**Link to docker hub or docker compose file on github**

https://github.com/hoppscotch/hoppscotch
https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build

**Additional context**

**Comment by vncloudsco** [comment]
Error 
```
2024-09-26 10:30:39
Backend Server | Error: Database migration not found. Please check the documentation for assistance: https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build#running-migrations
2024-09-26 10:30:39
Backend Server | at throwErr (/dist/backend/dist/utils.js:16:11)
2024-09-26 10:30:39
Backend Server | at InfraConfigService.initializeInfraConfigTable (/dist/backend/dist/infra-config/infra-config.service.js:66:38)
2024-09-26 10:30:39
Backend Server | at async InfraConfigService.onModuleInit (/dist/backend/dist/infra-config/infra-config.service.js:40:9)
2024-09-26 10:30:39
Backend Server | at async Promise.all (index 0)
2024-09-26 10:30:39
Backend Server | at async callModuleInitHook (/dist/backend/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_class-transformer@0.5.1_class-validator@0.14.1_refl_i5vxtddbnp5qhu6jmywguprp3e/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
2024-09-26 10:30:39
Backend Server | at async NestApplication.callInitHook (/dist/backend/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_class-transformer@0.5.1_class-validator@0.14.1_refl_i5vxtddbnp5qhu6jmywguprp3e/node_modules/@nestjs/core/nest-application-context.js:223:13)
2024-09-26 10:30:39
Backend Server | at async NestApplication.init (/dist/backend/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_class-transformer@0.5.1_class-validator@0.14.1_refl_i5vxtddbnp5qhu6jmywguprp3e/node_modules/@nestjs/core/nest-application.js:100:9)
2024-09-26 10:30:39
Backend Server | at async NestApplication.listen (/dist/backend/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_class-transformer@0.5.1_class-validator@0.14.1_refl_i5vxtddbnp5qhu6jmywguprp3e/node_modules/@nestjs/core/nest-application.js:169:33)
2024-09-26 10:30:39
Backend Server | at async bootstrap (/dist/backend/dist/main.js:69:5)
2024-09-26 10:30:39
Backend Server |
2024-09-26 10:30:39
Backend Server | Node.js v20.17.0
2024-09-26 10:30:39
Exiting process because Backend Server exited with code 1
``

**Comment by vncloudsco** [comment]
The error occurred due to the new version having changed, needing to update more information about the current database migration, there is currently no solution on cosmos to be able to run, in the future the image can be rebuilt


https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build#migrations
